### ISSUE TITLE
Issue working with detecting configuration for remote Selenium grids

### ISSUE THREAD

**Issue by msabbott** [barancev/webdriver-junit-archetype#2]
When configuring a Maven project, built from this archetype, to connect to a remote Selenium server or hub, the code to detected whether a grid hub URL has been configured does not correctly identify that this is the case.

The method SuiteConfiguration.hasProperty uses the method "properties.contains" - this is functionally equivalent to "properties.containsValue" (see Hashtable.contains docs: https://docs.oracle.com/javase/7/docs/api/java/util/Hashtable.html#contains(java.lang.Object) )

This is the incorrect method to use, and instead "properties.containsKey" method should be used instead.

**Comment by barancev** [comment]
Fixed by f18d5de9cc72bc14f5fd148505dd239181285e76
